import { Inter } from "next/font/google";
import "./globals.css";
import BgVideo from "./components/BgVideo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<BgVideo
					src={
						"https://vod-progressive.akamaized.net/exp=1699827589~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F2872%2F18%2F464364770%2F2058750301.mp4~hmac=24c550fb400932a52449ca70658bdd07409308814bc1f33004b59f649d5ef126/vimeo-prod-skyfire-std-us/01/2872/18/464364770/2058750301.mp4?download=1&filename=pexels-coldfire-5507081+%281080p%29.mp4"
					}
				/>
			</body>
		</html>
	);
}
